inherit_from: .rubocop_todo.yml

Layout/MultilineBlockLayout:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**.rb"

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/FormatString:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4.3
